
 version: 0.2
 
 phases:
   build:
    
    commands:
        - echo Entred the build phase
       
        - mvn test
        
    post_build: 
      commands: 
      
          - echo build completed successfully
          - mvn package
          
    artifacts: 
    files:
  
            - target/order-serviceKip.jar
            
    discard-paths: yes
  
