
 version: 0.2
 
 phases:
   build:
    
    commands:
        - echo Entred the build phase
        - mvn clean package
    post_build: 
     commands:
          - echo build completed successfully
          
    artifacts: 
       - target/order-serviceKip.jar
    discard-paths: yes
  
